"""Anomaly alert email formatter — cross-domain."""

from __future__ import annotations

from datetime import datetime
from typing import Any


class AnomalyAlertFormatter:
    """Formats HTML emails for anomaly detection alerts."""

    def format_subject(
        self,
        domain: str = "",
        anomaly_count: int = 0,
        **kwargs: Any,
    ) -> str:
        return f"[IMDR] ANOMALY ALERT | {domain.upper()} | {anomaly_count} anomalies detected"

    def format_body(
        self,
        domain: str = "",
        table_name: str = "",
        timestamp: datetime | None = None,
        anomalies: list[dict[str, Any]] | None = None,
        threshold_pct: float = 50.0,
        **kwargs: Any,
    ) -> str:
        anomalies = anomalies or []
        ts = timestamp.strftime("%Y-%m-%d %H:%M UTC") if timestamp else "N/A"

        parts = [
            "<html><body>",
            f"<h2>Anomaly Alert — {domain.upper()}</h2>",
            f"<p><b>Table:</b> {table_name}</p>",
            f"<p><b>Timestamp:</b> {ts}</p>",
            f"<p><b>Threshold:</b> {threshold_pct}%</p>",
            f"<p><b>Anomalies found:</b> {len(anomalies)}</p>",
        ]

        if anomalies:
            parts.append("<table border='1' cellpadding='5' cellspacing='0'>")
            parts.append(
                "<tr><th>Symbol</th><th>Series</th><th>Field</th>"
                "<th>Previous</th><th>Current</th><th>Change %</th></tr>"
            )
            for a in anomalies:
                parts.append(
                    f"<tr><td>{a.get('symbol', '')}</td>"
                    f"<td>{a.get('series', '')}</td>"
                    f"<td>{a.get('field', '')}</td>"
                    f"<td>{a.get('previous', '')}</td>"
                    f"<td>{a.get('current', '')}</td>"
                    f"<td>{a.get('pct_change', 0):.1f}%</td></tr>"
                )
            parts.append("</table>")

        parts.append("<hr><p><i>Generated by IMDR Anomaly Detection</i></p>")
        parts.append("</body></html>")
        return "\n".join(parts)
